Debug: false
DarktableBin: /usr/bin/darktable-cli
AssetsPath: /srv/photoprism
CachePath: /srv/photoprism/cache
OriginalsPath: /srv/photoprism/photos/originals
ImportPath: /srv/photoprism/photos/import
TempPath: /srv/photoprism/temp
HttpServerHost:
HttpMode: release
HttpPort: 81
HttpPassword:
DatabaseDriver: mysql
DatabaseDsn: tally_rw:A60e316b7b85f1850@tcp(newskydb.mysql.rds.aliyuncs.com:3306)/tally?charset=utf8mb4&parseTime=True&loc=Loca
Theme: lavendel
Language: english
